doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver: pdo_mysql
                dbname: '%env(DATABASE_NAME)%'
                host: '%env(DATABASE_HOST)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PWD)%'
                charset: utf8mb4
                mapping_types:
                    enum: string

    orm:
        mappings:
            eckinox:
                type: annotation
                dir: '%kernel.project_dir%/vendor/eckinox/eckinox-bundle/Entity'
                is_bundle: false
                prefix: Eckinox\Entity
                alias: Eckinox

framework:
    assets:
        packages:
            eckinox:
                base_path: bundles/eckinox/