doctrine:
    orm:
        mappings:
            eckinox:
                type: annotation
                dir: '%kernel.project_dir%/vendor/eckinox/eckinox-bundle/Entity'
                is_bundle: false
                prefix: Eckinox\Entity
                alias: Eckinox
        filters:
            archivedFilter:
                class: Eckinox\Library\Symfony\Doctrine\ArchivedFilter
                enabled: true
            localeFilter:
                class: Eckinox\Library\Symfony\Doctrine\LocaleFilter
                enabled: false
                # This filter is enabled in the LocaleSubscriber event subscriber

framework:
    translator:
        paths:
            - '%app.translations.custom%'
    assets:
        version_strategy: 'Eckinox\Library\General\Asset'
        packages:
            eckinox:
                base_path: bundles/eckinox/

twig:
    globals:
        available_locales: '%env(default:default_available_locales:available_locales)%'
