parameters:
    user_class: 'Eckinox\Entity\Application\User'
    user_form_type_class: 'Eckinox\Form\Application\UserType'

doctrine:
    orm:
        mappings:
            eckinox:
                type: annotation
                dir: '%kernel.project_dir%/vendor/eckinox/eckinox-bundle/Entity'
                is_bundle: false
                prefix: Eckinox\Entity
                alias: Eckinox
        filters:
            archivedFilter:
                class: Eckinox\Library\Symfony\Doctrine\ArchivedFilter
                enabled: true

framework:
    assets:
        version_strategy: 'Eckinox\Library\General\Asset'
        packages:
            eckinox:
                base_path: bundles/eckinox/
