# config/packages/security.yaml
security:
    encoders:
        Eckinox\Entity\Application\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: Eckinox\Entity\Application\User

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous: ~
        secured_area:
            pattern:   ^/
            anonymous: ~
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                always_remember_me: true
            form_login:
                login_path: login
                check_path: login
                use_referer: true
                default_target_path: /
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cron, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
